name: 'Approve + Merge Dependabot Pulls'

on: workflow_dispatch

jobs:
  worker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v3
        with:
          script: console.log(context)